build:
    stage: build
    script:
        - /home/rwash/.rbenv/versions/2.7.1/bin/jekyll build
    artifacts: 
        paths:
            - "_site"

deploy:
    stage: deploy
    dependencies:
        - build
    script:
        - rm -rf /var/www/rocinante
        - mv _site /var/www/rocinante
        - restorecon -R -v /var/www/rocinante
