build:
    script:
        - /home/rwash/.rbenv/versions/2.7.1/bin/jekyll build
    artifacts: 
        paths:
            - "_site"

deploy:
    script:
        - rm -rf /var/www/rocinante
        - mv _site /var/www/rocinante
